### ISSUE TITLE
Refactor Display.build and firstOption

### ISSUE THREAD

**Issue by zanddev** [ThatsPella/JetScape#1]
This method is not simple as it would be, maybe it is possible to explain what it exactly does and simplify it.

**Comment by zanddev** [comment]
Labels are ordered differently (**Records** should be over **Quit**).

**Comment by zanddev** [comment]
@ThatsPella required

**Comment by ThatsPella** [comment]
> @ThatsPella required

@GiacomoAmaa said he wants to fix it by himself.

**Comment by zanddev** [comment]
> 

assigned to him

**Comment by GiacomoAmaa** [comment]
pushed new working version on interface branch
