### ISSUE TITLE
Score moving 

### ISSUE THREAD

**Issue by GiacomoAmaa** [ThatsPella/JetScape#12]
in Display HUD se passi la stringa score + punteggio alla funzione tutte le volte si sposta la scritta. Idealmente dovresti calcolare solo le coordinate di score  e poi in un secondo momento quando vai a stampare aggiungi il punteggio alla stringa. (Vedi versione di interface)

**Comment by zanddev** [comment]
If I choose to display it not centered it could potentially go out of the window.
