### ISSUE TITLE
Problem with Barry

### ISSUE THREAD

**Issue by zanddev** [ThatsPella/JetScape#2]
Incidentally I discovered that Barry is somewhat unrelated / managed differently from other entities, so there is a particular case where the game is playing without Barry.

### How to reproduce
Copy **_DisplayMenu_** _GameState.INGAME_ row and put it into another source file that extends Display, so this row:
`		this.options.put("play", GameState.INGAME);
`
in another menu as _DisplayRecords_.

**Comment by GiacomoAmaa** [comment]
the first time the game must start from menu. A check prevents the player from being displayed if the first run is done elsewhere.
